# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  prontuario-db-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: prontuario-db
    volumes:
      - prontuario-db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=db-prontuario
      - MYSQL_USER=prontuario
      - MYSQL_PASSWORD=prontuario

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: prontuario-app
    volumes:
      - .:/var/www/app
    ports:
      - "81:8080"
    links:
      - mysql

