# v2 syntax
version: '3'

# Named volumes
volumes:
  # MySQL Data
  prontuario-db-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: prontuario-db
    volumes:
      - prontuario-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=!Q@W3e4r
      - MYSQL_DATABASE=db-prontuario
      - MYSQL_USER=prontuario
      - MYSQL_PASSWORD=prontuario

  # PHP (with Nginx)
  app:
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8000"
      - "81:8080"
    links:
      - mysql

